// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hocus-pocus/Current.tsx": () => import("../components/mockups/hocus-pocus/Current.tsx"),
  "./components/mockups/hocus-pocus/GraphiteAmber.tsx": () => import("../components/mockups/hocus-pocus/GraphiteAmber.tsx"),
  "./components/mockups/hocus-pocus/MidnightMint.tsx": () => import("../components/mockups/hocus-pocus/MidnightMint.tsx"),
  "./components/mockups/hocus-pocus/PlumPorcelain.tsx": () => import("../components/mockups/hocus-pocus/PlumPorcelain.tsx")
};
